export enum City {
    ALL="all",
    ARIANA="ariana",
    BEJA="beja",
    BEN_AROUS="ben arous",
    BIZERTE="bizerte",
    GABES="gabes",
    GAFSA="gafsa",
    JENDOUBA="jendouba",
    KAIROUAN="kairouan",
    KASSERINE="kasserine",
    Kebili="kebili",
    KEF="kef",
    MAHDIA="mahdia",
    MANOUBA="manouba",
    MEDENINE="medenine",    
    MONASTIR="monastir",
    NABEUL="nabeul",
    SFAX="sfax",
    SIDI_BOUZID="sidi bouzid",
    SILIANA="siliana",
    SOUSSE="sousse",
    TATAOUINE="tataouine",
    TOZEUR="tozeur",
    TUNIS="tunis",
    ZAGHOUAN="zaghouan",
}